CREATE PROCEDURE FI_SP_IncBeneficiario
    @CPF VARCHAR(14),
    @Nome VARCHAR(50),
    @IdCliente BIGINT
AS
BEGIN
    INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE)
    VALUES (@CPF, @Nome, @IdCliente);
    SELECT SCOPE_IDENTITY();
END;
